/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import forme.model.ModelTabeleIgra;
import javax.swing.JOptionPane;
import model.Igra;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Korisnik
 */
public class KlijentskaForma extends javax.swing.JFrame {

    
    private int brojPokusaja = 0;
    
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        ModelTabeleIgra mti = new ModelTabeleIgra();
        jTableIgra.setModel(mti);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPosalji = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelNaMestu = new javax.swing.JLabel();
        jLabelVanMesta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIgra = new javax.swing.JTable();
        jTextFieldBroj2 = new javax.swing.JTextField();
        jTextFieldBroj1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldBroj3 = new javax.swing.JTextField();
        jTextFieldBroj4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPosalji.setText("POSALJI");
        jButtonPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosaljiActionPerformed(evt);
            }
        });

        jLabel5.setText("Broj pogodjenih cifara koje JESU na svom mestu: ");

        jLabel6.setText("Broj pogodjenih cifara koje NISU na svom mestu: ");

        jLabelNaMestu.setText("0");

        jLabelVanMesta.setText("0");

        jTableIgra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableIgra);

        jTextFieldBroj2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTextFieldBroj2.setText("0");
        jTextFieldBroj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBroj2ActionPerformed(evt);
            }
        });

        jTextFieldBroj1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTextFieldBroj1.setText("0");

        jLabel7.setText("Broj 1: ");

        jLabel8.setText("Broj 2:");

        jLabel9.setText("Broj 3:");

        jLabel10.setText("Broj 4:");

        jTextFieldBroj3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTextFieldBroj3.setText("0");

        jTextFieldBroj4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTextFieldBroj4.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldBroj1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldBroj2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldBroj3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBroj4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jButtonPosalji)))
                        .addContainerGap(95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelVanMesta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNaMestu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBroj2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBroj1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBroj3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBroj4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButtonPosalji)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelNaMestu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelVanMesta))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosaljiActionPerformed
        
        if(!proveriUnos()){
            JOptionPane.showMessageDialog(null, "U svako polje mora biti upisana jedna cifra!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(brojPokusaja<=5){
           String kombinacija = jTextFieldBroj1.getText()+"-"+jTextFieldBroj2.getText()+"-"+jTextFieldBroj3.getText()+"-"+jTextFieldBroj4.getText();
        System.out.println(kombinacija);
        
        Igra igra = new Igra(-1, kombinacija, -1, -1);
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.POGADJAJ, igra);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
        /////////////////
        
        ServerskiOdgovor so = komunikacija.Komunikacija.getInstance().primiOdgovor();
        igra = (Igra) so.getOdgovor();
        
        brojPokusaja++;
        
        jLabelNaMestu.setText(String.valueOf(igra.getBrojPogodjenihNaMestu()));
        jLabelVanMesta.setText(String.valueOf(igra.getBrojPogodjenihNisuNaMestu()));
        
        ModelTabeleIgra mti = (ModelTabeleIgra) jTableIgra.getModel();
        mti.dodajIgru(igra); 
            
            if(igra.getBrojPogodjenihNaMestu()==4){
                JOptionPane.showMessageDialog(null, "CESTITAMO, POBEDILI STE!");
                
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Nemate vise pokusaja!", "Izgubili ste", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_jButtonPosaljiActionPerformed

    private void jTextFieldBroj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBroj2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBroj2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPosalji;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNaMestu;
    private javax.swing.JLabel jLabelVanMesta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableIgra;
    private javax.swing.JTextField jTextFieldBroj1;
    private javax.swing.JTextField jTextFieldBroj2;
    private javax.swing.JTextField jTextFieldBroj3;
    private javax.swing.JTextField jTextFieldBroj4;
    // End of variables declaration//GEN-END:variables

    private boolean proveriUnos() {
        
        boolean cifra1 = jTextFieldBroj1.getText().matches("[0-9]");
        boolean cifra2 = jTextFieldBroj2.getText().matches("[0-9]");
        boolean cifra3 = jTextFieldBroj3.getText().matches("[0-9]");
        boolean cifra4 = jTextFieldBroj4.getText().matches("[0-9]");
        
        if(cifra1 && cifra2 && cifra3 && cifra4){
            return true;
        }
        
        return false;
    }

    
}
